### ISSUE TITLE
would it be possible to perform projection mapping in a shader with this toolkit?

### ISSUE THREAD

**Issue by astraw** [JaneliaSciComp/janelia-unity-toolkit#125]
Hi,

I would like to create a completely seamless panoramic surround projected onto a cylinder with one projector by projecting both directly onto the "front" of the cylinder as well as onto mirrors to illuminate the "back" of the cylinder. As far as I am aware, but please correct me if I have missed it, this is not currently implemented with this toolkit.

I think reimplementing or porting the relevant parts of the display pipeline from [FreemoVR](https://github.com/strawlab/freemovr_engine) would enable this. The pipeline architecture of FreemoVR is shown in this picture (which illustrates illuminating a cylinder from 3 projectors, each with a direct and 2 mirror reflected projection paths):

![](https://raw.githubusercontent.com/strawlab/freemovr_engine/noetic/docs/architecture.png)

The "geometry texture" and "display view" textures are created using [shaders](https://github.com/strawlab/freemovr_engine/tree/noetic/src/shaders) and multipass render-to-texture rendering. Hopefully the diagram is somewhat understandable but I am happy to describe it in more detail.

Key here is that it is possible to render on arbitrary display surfaces (which requires a 3D model of them and the 3D position of the observer in addition to the simulated 3D world). This allows doing perspective-correct visual stimulation for freely moving animals. Also important is that there may be multiple, potentially overlapping, paths from projector to display and that these can be calibrated spatially and luminance-wise on a per-pixel level (which requires a calibration of the projector and display).

If it would be possible, what would you suggest as the first steps for someone to get started with such a reimplementation?

Thanks!

**Comment by hubbardp** [comment]
Hi, Andrew.  I apologize that I missed this issue (and I believe I have updated my settings so I won't miss any others).  Let me take a look at the documentation and code for FreemoVR before I give I more complete answer.  But in general, Unity does have good support for shaders and multiple passes, using the GPU, so I expect it could do the kind of remapping that I imagine would be the basis of your approach.

**Comment by hubbardp** [comment]
I did finally add some code that can render cylindrical panoramas in real time for a freely moving viewpoint.  There is some documentation here:

https://github.com/JaneliaSciComp/janelia-unity-toolkit/tree/master/org.janelia.camera-utilities#panoramic-display-on-non-flat-screens

And there is an example of usage here:

https://github.com/JaneliaSciComp/janelia-unity-toolkit/blob/master/org.janelia.camera-utilities/Runtime/ExampleUsingPanoramicDisplayCamera.cs

This approach does not directly support the additional mirrors mentioned above (although the underlying code can handle any display surface that can have the 3D position of each projected pixel described in textures) but it does have some support for extra textures to compensate for the loss of brightness and the addition of color artifacts at the borders between projectors.  Here is a picture of the brightness compensation and another picture of the color correction (where red is the artifact color being corrected for):
 
![panoBothCorrections](https://github.com/JaneliaSciComp/janelia-unity-toolkit/assets/32466564/b79184a2-0944-4094-81c1-55ab8a2fd00c)

**Comment by hubbardp** [comment]
I tried to put a considerable amount of description in the example of usage:

https://github.com/JaneliaSciComp/janelia-unity-toolkit/blob/master/org.janelia.camera-utilities/Runtime/ExampleUsingPanoramicDisplayCamera.cs

Maybe start reading of that file, and let me know if there are parts that could use further clarification?

**Comment by hubbardp** [comment]
Also, if you are feeling adventurous, you could look at the code that changed when I added this feature:

https://github.com/JaneliaSciComp/janelia-unity-toolkit/pull/160/files

The shader (which does ray casting to remap from the cube map to the display surface) is right near the top of that change list.

**Comment by astraw** [comment]
Thanks, I had looked at the usage example, but wasn't sure if I was missing something. Is it correct that the "geometry texture" in my image above is done implicitly and that the geometry is defined as a projector modeled by a pinhole camera and the display surface as a perfect cylinder? If so, that would clarify for me why I didn't find those aspects.

I will try this out at some point, although unfortunately not in the immediate future.

I am closing the issue, as you have certainly addressed it. :)
