### ISSUE TITLE
Logging: Set name of log file?

### ISSUE THREAD

**Issue by hjmh** [JaneliaSciComp/janelia-unity-toolkit#33]
Currently the name for the log file is just "Log_" + time stamp. It would be nice if it was possible to set a slightly more descriptive name. Maybe one could have a popup window just before starting to run the standalone player VR where the user has to enter a custom string that would be included in the file name?

**Comment by hubbardp** [comment]
The launcher UI now has a box for text that gets added to the log filename, after the date part.
https://github.com/JaneliaSciComp/janelia-unity-toolkit/pull/61
