### ISSUE TITLE
New feature: Set runtime duration for VR in standalone player mode

### ISSUE THREAD

**Issue by hjmh** [JaneliaSciComp/janelia-unity-toolkit#36]
At the moment the standalone player runs until it is manually quit. It would be convenient to have the program ran for a set period of time. Maybe this could be a value set in the editor?

**Comment by hubbardp** [comment]
There is now a "Session parameters" section in the launcher UI, in which the "timeoutSecs" value can be set.

https://github.com/JaneliaSciComp/janelia-unity-toolkit/pull/54
https://github.com/JaneliaSciComp/janelia-unity-toolkit/pull/55

Awaiting confirmation that this new functionality works as expected.

**Comment by hubbardp** [comment]
Confirmed to be working.
