### ISSUE TITLE
Log several parameters that can be adjusted in unity editor

### ISSUE THREAD

**Issue by hjmh** [JaneliaSciComp/janelia-unity-toolkit#52]
Specific parameters that should be logged:
- frame rate (see ForceRenderRate.cs)
- ball radius (see FicTracUpdater.cs )

**Comment by hubbardp** [comment]
The actual refresh rate (in Hz) on the target display is now logged.
https://github.com/JaneliaSciComp/janelia-unity-toolkit/pull/65

**Comment by hubbardp** [comment]
The FicTrac parameters, including the ball radius, are now logged.
https://github.com/JaneliaSciComp/janelia-unity-toolkit/pull/66

**Comment by hubbardp** [comment]
The FicTrac parameters, including the ball radius, are now logged.
https://github.com/JaneliaSciComp/janelia-unity-toolkit/pull/66
