### ISSUE TITLE
correct position update

### ISSUE THREAD

**Issue by hjmh** [JaneliaSciComp/janelia-unity-toolkit#68]
In  FicTracUpdater.cs from org.janelia.fictrac-collision the values from fictrac are scaled incorrectly. The correct scaling would be

float s = ficTracBallRadius; (instead of float s = ficTracBallRadius * Mathf.Rad2Deg;) in public Vector3? Translation()

and

float s = Mathf.Rad2Deg; (instead of float s = ficTracBallRadius * Mathf.Rad2Deg;) in public Vector3? RotationDegrees()

**Comment by hjmh** [comment]
I think this is still not fixed but it's pretty urgent to avoid confusion as I update other packages/

**Comment by hubbardp** [comment]
This problem should be fixed now, with this change:
https://github.com/JaneliaSciComp/janelia-unity-toolkit/pull/70/files
