### ISSUE TITLE
Change convention for coordinate system for fictrac input

### ISSUE THREAD

**Issue by hjmh** [JaneliaSciComp/janelia-unity-toolkit#74]
Rebekah and I noticed that we used a convention for the fictrac coordinate system that does not follow the instructions/descriptions in the fictrac documentation.

We used z - up, y - forward, x - right (see below):
![fictrac-configImg_HH_old](https://user-images.githubusercontent.com/10639803/125289970-d0044780-e2ed-11eb-8be3-14bf3b18799d.png)

The fictrac documentation assumes z - down, y - right,  x - forward as seen in the image below:
![fictrac-configImg_HH_new](https://user-images.githubusercontent.com/10639803/125290016-dd213680-e2ed-11eb-842b-1edc4e10a560.png)

To account for the change in coordinate system, we will need to change the positional update functions in unity. In **FicTracUpdater.cs** we will need to flip the values used for forward and sideways updates and invert the heading update. 

```
public Vector3? Translation()
{
    float s = ficTracBallRadius;
    float forward = _deltaRotationVectorLabUpdated[1] * s; // was 0
    float sideways = _deltaRotationVectorLabUpdated[0] * s; // was 1
    return new Vector3(forward, 0, sideways);
}
public Vector3? RotationDegrees()
{
    float s = Mathf.Rad2Deg;
    float heading = _deltaRotationVectorLabUpdated[2] * s;
    return new Vector3(0, -heading, 0);  // inserted minus
}
```

**Comment by hubbardp** [comment]
This bug should now be fixed with this code change:
https://github.com/JaneliaSciComp/janelia-unity-toolkit/pull/76
