### ISSUE TITLE
option to correct for back projected image?

### ISSUE THREAD

**Issue by hjmh** [JaneliaSciComp/janelia-unity-toolkit#75]
The projected image needs to be mirrored if back-projected onto a screen. Some but not all projectors have the option to correct for this.

**Comment by hubbardp** [comment]
In `org.janelia.camera-utilities`, the `AdjoiningDisplaysCamera` has a `mirror` setting.  Changing it to `true` should give the correct behavior for back-projection onto a screen.  Let me know how it works.

**Comment by hjmh** [comment]
Yes this works!
